### ISSUE TITLE
Web Application

### ISSUE THREAD

**Issue by jinningwang** [CURENT/agvis#23]
----
08/30/2023

We can have a different way to implement the online web application of AGVis, because we have both a server and a domain to deploy the web application.

-------
03/20/2023

Create an online web application of AGVis using Pyodide, some examples:
[MATPOWER App](https://matpower.app/) by Richard Lincoln
[Pyodide Doc](https://pyodide.org/en/stable/index.html)

**Comment by jinningwang** [comment]
AGVis is developed with JavaScript and served through the python library HTTP. server. However, [http.server](https://docs.python.org/3/library/http.server.html#module-http.server) is not recommended for production. It only implements [basic security checks](https://docs.python.org/3/library/http.server.html#http-server-security).

Not sure if it is necessary to transfer to other web frameworks such as Flask, Django, or Pyramid.

**Comment by jinningwang** [comment]
Previously I developed a simple code interface to wrap the command line usage of agvis, and more details can be found in 
[agvis run](https://ltb.readthedocs.io/projects/agvis/en/latest/getting_started/tutorial/cli.html#agvis-run).

If we do switch to another framework, we might need to ensure the compatibility of this command line usage.

**Comment by zmalkmus** [comment]
When changing to the flask framework, I made sure that the agvis run command maintained full functionality with the exception of the static parameter, as flask only accepts static files from a specific directory.

**Comment by jinningwang** [comment]
This development issue can be separated as three stages.
1. Host AGVis online and enable topology visualization with built-in or user upload file.
2. Enable dynamic animation in the online application.
3. Maybe enable fully featured AGVis in the web application.
