### ISSUE TITLE
Functionality: Low performance with MS Edge browser

### ISSUE THREAD

**Issue by jinningwang** [CURENT/agvis#34]
When using ANDES, DiME, and AGVis, together, I ran into an issue, the visualization using MS Edge browser is a lot behind the ANDES simulation speed. After switching to Google Chrome, the issue disappeared.

All three modules, namely ANDES, DiME, and AGVis, are running on WSL, Ubuntu 22.04.
MS Edge browser is running on win10.
ANDES is running in [quasi-real-time mode](https://docs.andes.app/en/latest/configref.html?highlight=quasi-real-time#tds) with an IEEE 39-bus system. 

If this is the case, we might need to mark this as a known issue in the documentation.

**Comment by nparsly** [comment]
I did some tests with MS Edge using both the IDR for running simulations and the federated use with ANDES and DiME. I did not experience any slow down, so this may have just been a hardware problem, though I'll look into it further.

**Comment by jinningwang** [comment]
Thanks for your efforts on this. I suggest that we could add a clarification to the documentation, including a mention of using "private browsing mode" (also known as "incognito mode") as the "Igniot window". Additionally, if users experience performance issues, we can suggest trying another browser or disabling any ad blockers or other browser extensions that may be interfering with the application.

> I did some tests with MS Edge using both the IDR for running simulations and the federated use with ANDES and DiME. I did not experience any slow down, so this may have just been a hardware problem, though I'll look into it further.

**Comment by jinningwang** [comment]
It turned out to be an issue with the MS Edge browser itself, rather than AGVis. It had been addressed by switching to Google Chrome.
