### ISSUE TITLE
Does AGVIS support substation oneline diagram?

### ISSUE THREAD

**Issue by mzy2240** [CURENT/agvis#61]
is it possible to view the inner-substation topology (oneline diagram) using Agvis?

**Comment by jinningwang** [comment]
We don't have such function in AGVis right now, but ANDES has a interface that supports similar visualization: https://docs.andes.app/en/latest/examples/pypowsybl.html

In addition, do you have any more detail examples, such as a screenshot or something? We might consider it in the future development.

**Comment by jinningwang** [comment]
Close for now as not a feature in plan.
