### ISSUE TITLE
Docker usage issue with version 3.2.1.post46+g8f69adc

### ISSUE THREAD

**Issue by jinningwang** [CURENT/agvis#62]
The docker build function failed on my end. I am using Mac OS, and additional error message is excerpted below.

```bash
(ltb) jinningwang@jwmba-3 agvis % agvis

    _   _____   ___     | Version 3.2.1.post46+g8f69adc
   /_\ / __\ \ / (_)___ | Python 3.11.6 on Darwin, 10/20/2023 03:16:01 PM
  / _ \ (_ |\ V /| (_-< | 
 /_/ \_\___| \_/ |_/__/ | Web-based geographical visualizer.

usage: agvis [-h] [-v {1,10,20,30,40}] {run,misc,selftest,st,demo} ...

positional arguments:
  {run,misc,selftest,st,demo}
                        [run] serve the web; [selftest] run self test;

options:
  -h, --help            show this help message and exit
  -v {1,10,20,30,40}, --verbose {1,10,20,30,40}
                        Verbosity level in 10-DEBUG, 20-INFO, 30-WARNING, or 40-ERROR.
(ltb) jinningwang@jwmba-3 agvis % ./go.sh build
./go.sh: line 48: syntax error near unexpected token `newline'
./go.sh: line 48: `    google-chrome --incognito http://localhost:8810/ 2> /dev/null > /dev/null &!'
```

**Comment by zmalkmus** [comment]
Nevermind, I see the issue. I accidentally added a '!' at the end of the line that failed. That is not valid syntax and it is weird that the script would even compile on my end. The issue should be fixed on develop.

**Comment by jinningwang** [comment]
I was using Mac OS.

BTW, in the excerpted preamble function, there is a line says, "Python 3.11.6 on Darwin, 10/20/2023 03:16:01 PM". Three most common options are Windows, Linux, and Darwin, where Darwin is the core UNIX OS of Mac OS.

> I tested ./go.sh build and ./go.sh dev2 on the develop branch and it works on Linux. Can you tell me the branch you are using and can you send me the go.sh file that caused the issue?

**Comment by jinningwang** [comment]
Is it possible to include the Docker part check as part of [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow)?

In the AGVis unit test part, we can focus on the Python module functionality, whereas Docker is hard to be included here. Therefore, GitHub flow can be a good choice as the Docker functionality test.

**Comment by zmalkmus** [comment]
By GitHub flow do you mean creating a separate branch specifically for Docker testing? 

I might be able to include the ./go.sh commands as a part of the agvis test command, but I have not looked into this yet.

**Comment by jinningwang** [comment]
> By GitHub flow do you mean creating a separate branch specifically for Docker testing?
> 
> I might be able to include the ./go.sh commands as a part of the agvis test command, but I have not looked into this yet.

GitHub flow means, we can pre-define some jobs in the AGVis repository. Then, GitHub will create some check on PR, where we can include some complex testing actions. Such as building documentation on ReadTheDocs, running built-in AGVis tests.

Not sure which one is more easier, we can discuss on next Monday's monthly meeting if you can attend it.
