### ISSUE TITLE
Visualization enhancement: base-map switch and map zoom-in limitation

### ISSUE THREAD

**Issue by jinningwang** [CURENT/agvis#70]
**Issue**
When using AGVis, the zoom-in seems to be limited somewhere, as shown in the Figure below:

![image](https://github.com/CURENT/agvis/assets/79226045/9aca0cc2-5ac3-44b8-9f23-8e7281aa5f54)

**Desire Feature**
First, improve zoom-in limitation.
Can we made some change to alleviate this limitation so AGVis is capable of distribution system visualization? For example, a microgrid on UTK Campus size as attached in the case file. [UTCampus.xlsx](https://github.com/CURENT/agvis/files/14385180/UTCampus.xlsx)

Second, is it possible to add option to switch base-map? Maybe street-map?

**Version**
```bash
(agvis) jinningwang@jwmba-3 agvis % agvis run

    _   _____   ___     | Version 3.2.1.post96+gbd5488c
   /_\ / __\ \ / (_)___ | Python 3.9.18 on Darwin, 02/23/2024 07:18:28 AM
  / _ \ (_ |\ V /| (_-< | 
 /_/ \_\___| \_/ |_/__/ | Web-based geographical visualizer.

Working directory: "/Users/jinningwang/Documents/work/agvis"
AGVis will serve static files from directory "/Users/jinningwang/Documents/work/agvis/agvis/static"
at the URL http://127.0.0.1:8810. Open your web browser and navigate to the URL to access the application.

Starting AGVis... Press Ctrl+C to stop.

[2024-02-23 07:18:28 -0500] [63127] [INFO] Starting gunicorn 21.2.0
[2024-02-23 07:18:28 -0500] [63127] [INFO] Listening at: http://127.0.0.1:8810 (63127)
[2024-02-23 07:18:28 -0500] [63127] [INFO] Using worker: sync
[2024-02-23 07:18:28 -0500] [63128] [INFO] Booting worker with pid: 63128
```

**Comment by zmalkmus** [comment]
I apologize for the late reply. It is possible leaflet has been set to have a max zoom, which can be overridden with a single value change, otherwise, this is a limiting factor with the leafletjs library. I will look into this.
